name: "Generate README.md File"
description: "Rebuilds the README.md From Scratch"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: pip

    - name: Install Dependencies
      run: python -m pip install -r requirements.txt

    - name: Generate README.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make generate_readme
