name: Generate README.md File

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main
  # TODO: Remove `push` later
  push:
    branches:
      - first_pass

jobs:
  test:
    name: Generate README.md File
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout Repository
      uses: actions/checkout@master

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: pip

    - name: Install Dependencies
      run: python -m pip install -r requirements.txt

    - name: Generate README.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make generate_readme

    - name: Commit + Push Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "docs(readme): Auto-generate plugins list"
        commit_user_name: "github-actions[bot]"
        commit_user_email: "github-actions[bot]@users.noreply.github.com"
        commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
